#!/bin/bash

if [[ $# -lt 4 ]] ; then
    echo 'Usage: moor <image> <tag> <host_cmd> <container_cmd>'
    echo '  <image>         - docker image which contains required command'
    echo '  <tag>           - docker image tag'
    echo '  <host_cmd>      - how to name the command on the host'
    echo '  <container_cmd> - command to run in the container'
    exit 0
fi

IMAGE=$1
TAG=$2
NAME=$3
CMD=$4

# Host
BIN=~/.local/bin
MOORHOME=.moor/home
mkdir -p $HOME/$MOORHOME

# Container
WORKDIR=/workdir

printf \
'GID=$(id -g $USER)

docker run -i --rm \
--network=host \
--ipc=host \
--workdir '$WORKDIR' \
--volume $PWD:'$WORKDIR' \
--volume $HOME/'$MOORHOME':$HOME \
--user $UID:$GID \
--env HOME=$HOME \
'$IMAGE':'$TAG' \
'$CMD' \
"$@"

' > $BIN/$NAME && chmod +x $BIN/$NAME
